# Generated by Django 5.1.7 on 2025-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
